<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>main</name>
   <tag></tag>
   <elementGuidId>953f7126-a976-4957-87c5-c1dc076254cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//main[@id='main']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//main[@id='main']</value>
   </webElementProperties>
</WebElementEntity>
