<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Title</name>
   <tag></tag>
   <elementGuidId>d64ccfd1-83c9-4fa3-98dd-97cb21e29185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//main[@id='main']/div/table/tbody/tr[${row}]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//main[@id='main']/div/table/tbody/tr[${row}]/td[2]</value>
   </webElementProperties>
</WebElementEntity>
